######################## default configuration ####################
baseURL = "https://landscapegeoinformatics.github.io/2024_foss4g_europe/"
title = "FOSS4G Europe 2024"
theme = "eventre-hugo"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "America/New_York"
# post pagination
paginate = 6 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# google analytics
googleAnalytics = "UA-123456-78" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = [
] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage


############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ##############################
[outputs]
home = ["HTML"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = ""
[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""
[[params.plugins.css]]
link = "plugins/font-awesome/font-awesome.min.css"
attributes = ""
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/mixitup/mixitup.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/syotimer/syotimer.min.js"
attributes = ""
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = ""


####################### navigation ##########################

# main menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

# [[menu.main]]
# name = "Speaker"
# url = "speaker/"
# weight = 3

# [[menu.main]]
# name = "Blog"
# url = "blog/"
# weight = 4

# [[menu.main]]
# weight = 5
# name = "Pages"
# hasChildren = true

#  [[menu.main]]
#  parent = "Pages"
#  name = "Gallery"
#  url = "gallery/"

#  [[menu.main]]
#  parent = "Pages"
#  name = "FAQ"
#  url = "faq/"

#  [[menu.main]]
#  parent = "Pages"
#  name = "Pricing"
#  url = "pricing/"

#  [[menu.main]]
#  parent = "Pages"
#  name = "Schedule"
#  url = "schedule/"

#  [[menu.main]]
#  parent = "Pages"
#  name = "Testimonial"
#  url = "testimonial/"
  
[[menu.main]]
name = "Contact"
url = "contact/"
weight = 6



#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_footer = "images/logo.png"
logo_width = "100px"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = false
label = "Buy Ticket"
icon = "images/icon/ticket.png"
link = "contact/"

# Subscription
# [params.subscription]
# enable = true
# title = "Subscribe to Our Newsletter"
# content = "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusm tempor"
# mailchimp subsciption
# mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
# mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
name = "Tartu University"
location = "Ülikooli,Tartu,<br> Estonia."
email = "TBA"
link = "#"

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################
# [[params.social]]
# title = "facebook"
# icon = "fa-facebook" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
# link = "#"

[[params.social]]
title = "twitter"
icon = "fa-twitter" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://twitter.com/foss4ge"

[[params.social]]
title = "mastodon"
icon = "fa-mastodon" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://fosstodon.org/@foss4geurope"

[[params.social]]
title = "github"
icon = "fa-github" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://github.com/LandscapeGeoinformatics/2024_foss4g_europe"

# [[params.social]]
# title = "linkedin"
# icon = "fa-linkedin" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
# link = ""
